### ISSUE TITLE
text selection

### ISSUE THREAD

**Issue by mpolci** [twinwallet/twinwallet-recovery#6]
text selection is disabled, should be enabled

**Comment by caraffa** [comment]
Actually this a Ionic "feature" (bug? Se Ionic issue #5612: No text selection for any element other then input fields). This is forcing the developer to use input tags where other elements (p, labels, etc.) would better fit the needs.

**Comment by mpolci** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sx5dMxeN&#x2F;40-twinwallet-recovery-issue-6-text-selection"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> twinwallet recovery issue #6: text selection</a>
